source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'InfiniteeUI_Example' do
  
  pod 'JPLiquidLayout'
  pod 'JPBasic'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'Shimmer'
  pod 'YYWebImage'
  
  target 'InfiniteeUI_Tests' do
    inherit! :search_paths

    
  end
end
